# Generated by Django 3.2.5 on 2021-07-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ABM', '0001_initiala'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=64)),
                ('lista', models.CharField(max_length=64)),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=1200),
        ),
    ]
